// common_c_structs.h
#ifndef COMMON_C_STRUCTS_H
#define COMMON_C_STRUCTS_H

#include <stddef.h>
#pragma pack(push,1)
struct levlset {
    double epsilon_ls;
    double epsilon_lsd;
    double dtlset;
    double dtlset_cfl;
    double redist_toler;
    double redist_toler_curr;
    double r_int_buffer;
    double r_int_elem_size;
    double phvol[2];
    double AdjRedistVelCFL;
    double BubRad;
    double vf_target;
    double C_int_adjust;
    double vf_now;
    double vfcontrcoeff;
    double C_int_cap;
    double epsilonBT;

    double xdistancesum;
    double ydistancesum;
    double zdistancesum;
    double totalxdist;
    double totalydist;
    double totalzdist;
    double avgxdistance;
    double avgydistance;
    double avgzdistance;
    double avgxdistold;
    double avgydistold;
    double avgzdistold;
    double xdistideal;
    double ydistideal;
    double zdistideal;
    double dx_new;
    double dy_new;
    double dz_new;
    double ddxvel;
    double ddyvel;
    double ddzvel;
    double xvelsum;
    double yvelsum;
    double zvelsum;
    double totalxvel;
    double totalyvel;
    double totalzvel;
    double avgxvel;
    double avgyvel;
    double avgzvel;
    double avgxvelold;
    double avgyvelold;
    double avgzvelold;
    double velwghtsum;
    double totalvelwght;
    double bubvolsum;
    double totbubvol;
    double denssum;
    double totbubdens;
    double xcforcesum;
    double ycforcesum;
    double zcforcesum;
    double totalxcforce;
    double totalycforce;
    double totalzcforce;
    double totalxcforceold;
    double totalycforceold;
    double totalzcforceold;
    double avgxcforce;
    double avgycforce;
    double avgzcforce;
    double avgxcforceold;
    double avgycforceold;
    double avgzcforceold;
    double avgxcf;
    double avgycf;
    double avgzcf;
    double x_c_f;
    double y_c_f;
    double z_c_f;
    double xforcenewtsum;
    double yforcenewtsum;
    double zforcenewtsum;
    double totxfnewtsum;
    double totyfnewtsum;
    double totzfnewtsum;
    double xcfnewtons;
    double ycfnewtons;
    double zcfnewtons;
    double rholiq;
    double rhogas;
    double coalbubrad;
    double avgxcoordold[100];
    double avgycoordold[100];
    double avgzcoordold[100];

    int i_res_cf;
    int nzinBsum;
    int ntotnzinB;

    int iLSet;
    int iuse_vfcont_cap;
    int i_num_bubbles;
    int ivconstraint;
    int iSolvLSSclr1;
    int iSolvLSSclr2;
    int i_redist_loop_flag;
    int i_redist_max_iter;
    int i_spat_var_eps_flag;
    int i_dtlset_cfl;
    int i_check_prox;
    int i_gradphi;
    int i_focusredist;
    int i_AdjRedistVel;
    int buintcfl;
    int iBT;
    int iFT;
    int icoalCtrl;
    int coalcon;
    int update_coalcon;
    int coaltimtrak;
    int coalest;
    int coalcon_rem[100];
};
#pragma pack(pop)

#endif // COMMON_C_STRUCTS_H
